version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: streaming-lp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: streaming-lp-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"


